- markdown: |
    Reminder: Please update the DB Readme and ensure SQL migrations are reversible (include rollback scripts if applicable).
  pathFilter:
    - "database/sql/**"

- markdown: |
    Reminder: Please consider backward compatibility when modifying the API specification. 
    If breaking changes are unavoidable, ensure:
    - You communicate the changes to affected teams.
    - You provide proper versioning and migration mechanisms.
  pathFilter:
    - "**/openapi.yml"
