- markdown: |
    Reminder: Please update the [DB Readme](https://github.com/cowprotocol/services/blob/644ffb373cc9f52b3a0399fbae2a6d86b0268668/database/README.md).
    If creating new tables, update the [tables list](https://github.com/cowprotocol/services/blob/main/crates/database/src/lib.rs#L51-L87).
    When adding a new index, consider using `CREATE INDEX CONCURRENTLY` for tables involved in the critical execution path.
  pathFilter:
    - "database/sql/**"

- markdown: |
    Reminder: Please consider backward compatibility when modifying the API specification. 
    If breaking changes are unavoidable, ensure:
    - You explicitly pointed out breaking changes.
    - You communicate the changes to affected teams (at least Frontend team and SAFE team).
    - You provide proper versioning and migration mechanisms.
  pathFilter:
    - "**/openapi.yml"
