[package]
name = "tenderly-deploy-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contracts = { path = "../contracts" }
web3 = "0.18"
tokio = { version = "1.22", features = ["macros", "rt-multi-thread", "signal", "time"] }
reqwest = "0.11"
serde_json = "1.0"
log = "0.4"
simple_logger = "4.1"
serde.workspace = true
hex.workspace = true
