services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5552:5552"
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_stream advertised_host localhost
    command: bash -c "rabbitmq-plugins enable rabbitmq_stream --offline && rabbitmq-server"
