chain-id = "100"  # Gnosis Chain
weth = "0xe91D153E0b41518A2Ce8Dd3D7944Fa863463a97d"  # wxDAI on Gnosis Chain
base-tokens = []
max-hops = 2
max-partial-attempts = 5
native-token-price-estimation-amount = "100000000000000000" 