-- Start storing the solver that provided the winning quote for CIP-27.
-- https://snapshot.org/#/cow.eth/proposal/0x64e061568e86e8d2eec344d4a892e4126172b992cabe59a0b24c51c4c7e6cc33
--
-- We are using the 0 address for quotes where we historically didn't store the solver address
-- and for trivial quotes which have been generated by the `SanitizedPriceEstimator`.
ALTER TABLE quotes ADD COLUMN solver bytea NOT NULL DEFAULT '\x0000000000000000000000000000000000000000';
ALTER TABLE order_quotes ADD COLUMN solver bytea NOT NULL DEFAULT '\x0000000000000000000000000000000000000000';

-- Drop defaults again because the solver address should not be optional.
ALTER TABLE quotes ALTER COLUMN solver DROP DEFAULT;
ALTER TABLE order_quotes ALTER COLUMN solver DROP DEFAULT;
