node-url = "http://chain:8545"
simulation-node-url = "http://chain:8545"

[logging]
filter = "warn,autopilot=debug,shared=info,price_estimation=info"

[current-block]
poll-interval = "1s"

[run-loop]
solve-deadline = "20s"

[[gas-estimators]]
type = "Web3"

[[gas-estimators]]
type = "Alloy"

[[drivers]]
name = "baseline"
url = "http://driver/baseline"
address = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720"

[fee-policies]

[database]
write-url = "%DB_WRITE_URL"
read-url = "%DB_READ_URL"

[ethflow]
contracts = ["0x04501b9b1d52e67f6862d157e00d13419d2d6e95"]
skip-event-sync = true

[order-quoting]
price-estimation-drivers = [{ name = "baseline", url = "http://driver/baseline" }]

[native-price-estimation]
estimators = [[{ type = "Driver", name = "baseline", url = "http://driver/baseline" }]]

[native-price-estimation.cache]
max-age = "20m"
