eip1271-skip-creation-validation = true

[shared]
node-url = "http://chain:8545"
simulation-node-url = "http://chain:8545"

[order-quoting]
price-estimation-drivers = [{ name = "baseline", url = "http://driver/baseline" }]

[native-price-estimation]
estimators = [[{ type = "Driver", name = "baseline", url = "http://driver/baseline" }]]

[database]
write-url = "%DB_WRITE_URL"
read-url = "%DB_READ_URL"
