[package]
name = "number-conversions"
version = "0.1.0"
authors = ["Cow Protocol Developers <dev@cow.fi>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
bigdecimal = "0.3"
num = "0.4"
primitive-types = { version = "0.10" }
