// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script} from "forge-std/Script.sol";
import {console} from "forge-std/console.sol";

contract GenerateConfigs is Script {
    function run() public {
        // Read addresses from environment
        address weth = vm.envAddress("WETH_ADDRESS");
        address dai = vm.envAddress("DAI_ADDRESS");
        address usdc = vm.envAddress("USDC_ADDRESS");
        address uniswapV2Router = vm.envAddress("UNISWAP_V2_ROUTER_ADDRESS");
        address uniswapV2Factory = vm.envAddress("UNISWAP_V2_FACTORY_ADDRESS");
        address settlementContract = vm.envAddress("SETTLEMENT_CONTRACT_ADDRESS");
        address authenticator = vm.envAddress("AUTHENTICATOR_ADDRESS");
        address vaultRelayer = vm.envAddress("VAULT_RELAYER_ADDRESS");
        address balancerVault = vm.envAddress("BALANCER_VAULT_ADDRESS");

        // Generate driver.toml
        string memory driverToml = string.concat(
            'app-data-fetching-enabled = true\n',
            'orderbook-url = "http://orderbook"\n',
            'tx-gas-limit = "45000000"\n',
            '\n',
            '[[solver]]\n',
            'name = "baseline" # Arbitrary name given to this solver, must be unique\n',
            'endpoint = "http://baseline"\n',
            'absolute-slippage = "40000000000000000" # Denominated in wei, optional\n',
            'relative-slippage = "0.1" # Percentage in the [0, 1] range\n',
            '# Anvil account #0 private key (from test mnemonic)\n',
            'account = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"\n',
            '\n',
            '[submission]\n',
            'gas-price-cap = "1000000000000"\n',
            '\n',
            '[[submission.mempool]]\n',
            'mempool = "public"\n',
            '\n',
            '[liquidity]\n',
            'base-tokens = [\n',
            '    "', vm.toString(weth), '", # WETH (auto-generated from deployment)\n',
            '    "', vm.toString(dai), '", # DAI (auto-generated from deployment)\n',
            '    "', vm.toString(usdc), '", # USDC (auto-generated from deployment)\n',
            ']\n',
            '\n',
            '[[liquidity.uniswap-v2]] # Uniswap V2 configuration (auto-generated from deployment)\n',
            'router = "', vm.toString(uniswapV2Router), '"\n',
            'pool-code = "0x96e8ac4277198ff8b6f785478aa9a39f403cb768dd02cbee326c3e7da348845f" # Uniswap V2 init code hash\n',
            'missing-pool-cache-time = "1h"\n'
        );

        // Generate baseline.toml
        string memory baselineToml = string.concat(
            'chain-id = "31337" # Anvil local chain\n',
            'base-tokens = [\n',
            '    "', vm.toString(weth), '", # WETH (auto-generated from deployment)\n',
            '    "', vm.toString(dai), '", # DAI (auto-generated from deployment)\n',
            '    "', vm.toString(usdc), '", # USDC (auto-generated from deployment)\n',
            ']\n',
            'max-hops = 2\n',
            'max-partial-attempts = 5\n',
            'native-token-price-estimation-amount = "100000000000000000" # 0.1 ETH\n'
        );

        // Generate .env.offline for docker-compose
        string memory envOffline = string.concat(
            '# Auto-generated by 06_GenerateConfigs.s.sol\n',
            '# Generated at: ', vm.toString(block.timestamp), '\n',
            '\n',
            '# Network Configuration\n',
            'CHAIN_ID=31337\n',
            'NODE_URL=http://chain:8545\n',
            'SIMULATION_NODE_URL=http://chain:8545\n',
            '\n',
            '# Token Addresses (from deployment)\n',
            'WETH_ADDRESS=', vm.toString(weth), '\n',
            'DAI_ADDRESS=', vm.toString(dai), '\n',
            'USDC_ADDRESS=', vm.toString(usdc), '\n',
            'NATIVE_TOKEN_ADDRESS=', vm.toString(weth), '\n',
            '\n',
            '# Uniswap V2 Addresses (from deployment)\n',
            'UNISWAP_V2_FACTORY_ADDRESS=', vm.toString(uniswapV2Factory), '\n',
            'UNISWAP_V2_ROUTER_ADDRESS=', vm.toString(uniswapV2Router), '\n',
            '\n',
            '# CoW Protocol Addresses (from deployment)\n',
            'SETTLEMENT_CONTRACT_ADDRESS=', vm.toString(settlementContract), '\n',
            'AUTHENTICATOR_ADDRESS=', vm.toString(authenticator), '\n',
            'VAULT_RELAYER_ADDRESS=', vm.toString(vaultRelayer), '\n',
            'BALANCER_VAULT_ADDRESS=', vm.toString(balancerVault), '\n'
        );

        // Write TOML files to poc-offline-mode/configs/
        vm.writeFile("./configs/driver.toml", driverToml);
        vm.writeFile("./configs/baseline.toml", baselineToml);
        
        // Write .env.offline to playground/
        vm.writeFile("../.env.offline", envOffline);

    }
}
