FROM docker.io/clux/muslrust:1.55.0-openssl11 as cargo-build
WORKDIR /usr/src/oba-services

# Copy and Build Code
COPY . .
RUN env CARGO_PROFILE_RELEASE_DEBUG=1 cargo build --target x86_64-unknown-linux-musl --release

RUN \
    cd .. && \
    git clone https://github.com/gnosis/regex-stream-split.git && \
    cd regex-stream-split && \
    git checkout edc88224612b9e151c334fa6d3a7d20575d83836 && \
    cargo build --target x86_64-unknown-linux-musl --release

# Extract Binary
FROM docker.io/alpine:latest

# Handle signal handlers properly
RUN apk add --no-cache tini
COPY --from=cargo-build /usr/src/regex-stream-split/target/x86_64-unknown-linux-musl/release/regex-stream-split /usr/local/bin/regex-stream-split
COPY --from=cargo-build /usr/src/oba-services/target/x86_64-unknown-linux-musl/release/orderbook /usr/local/bin/orderbook
COPY --from=cargo-build /usr/src/oba-services/target/x86_64-unknown-linux-musl/release/solver /usr/local/bin/solver
COPY --from=cargo-build /usr/src/oba-services/target/x86_64-unknown-linux-musl/release/alerter /usr/local/bin/alerter
COPY docker/startup.sh /usr/local/bin/startup.sh

CMD echo "Specify binary - either solver or orderbook"
ENTRYPOINT ["/sbin/tini", "--", "startup.sh"]
