FROM docker.io/rust:1-slim-bullseye as cargo-build

# Copy and build code
WORKDIR /src
RUN apt-get update && apt-get install -y git libssl-dev pkg-config curl tar
COPY . .
WORKDIR /src/crates/dev-geth
RUN CARGO_PROFILE_RELEASE_DEBUG=1 cargo build --release

# Install geth via curl
WORKDIR /geth
RUN curl https://gethstore.blob.core.windows.net/builds/geth-linux-amd64-1.10.26-e5eb32ac.tar.gz -o geth.tar.gz
RUN tar -xf geth.tar.gz

# Extract binary
FROM docker.io/debian:bullseye-slim
COPY --from=cargo-build /src/target/release/dev-geth /usr/local/bin/
COPY --from=cargo-build /geth/geth-linux-amd64-1.10.26-e5eb32ac/geth /usr/local/bin/

ENTRYPOINT ["dev-geth"]
