use crate::{
    domain::{auction, notification, solution},
    infra::metrics,
};

pub mod baseline;
pub mod legacy;

pub use self::{baseline::Baseline, legacy::Legacy};

pub enum Solver {
    Baseline(Baseline),
    Legacy(Legacy),
}

impl Solver {
    /// Solves a given auction and returns multiple solutions. We allow
    /// returning multiple solutions to later merge multiple non-overlapping
    /// solutions to get one big more gas efficient solution.
    pub async fn solve(&self, auction: auction::Auction) -> Vec<solution::Solution> {
        metrics::solve(&auction);
        let deadline = auction.deadline.clone();
        let solutions = match self {
            Solver::Baseline(solver) => solver.solve(auction).await,
            Solver::Legacy(solver) => solver.solve(auction).await,
        };
        metrics::solved(&deadline, &solutions);
        solutions
    }

    /// Notifies the solver about important events. Some of those events are
    /// generated by the solver engine, others by the driver.
    pub fn notify(&self, notification: notification::Notification) {
        match self {
            Solver::Baseline(_) => (),
            Solver::Legacy(solver) => solver.notify(notification),
        }
    }
}
