[package]
name = "cow-solana-rpc"
version = "0.1.0"
edition = "2024"
description = "Solana JSON-RPC client wrapper for CoW Protocol"
license = "GPL-3.0-or-later"

[lib]
name = "cow_solana_rpc"
path = "src/lib.rs"

[dependencies]
futures = { workspace = true }
itertools = { workspace = true }
solana-commitment-config = { workspace = true }
solana-rpc-client = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-sdk = { workspace = true }
url = { workspace = true }

[features]
# Enables mock constructors for tests.
test-util = []

[lints]
workspace = true
