[package]
name = "global-metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.9"
prometheus = "0.13"
prometheus-metric-storage = { git = "https://github.com/cowprotocol/prometheus-metric-storage" , tag = "v0.4.0" }
