[package]
name = "global-metrics"
version = "0.1.0"
authors = ["Cow Protocol Developers <dev@cow.fi>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
once_cell = { workspace = true }
prometheus = { workspace = true }
prometheus-metric-storage = { workspace = true }
