relative-slippage = "0.1"
absolute-slippage = "0.02"

[dex]
excluded-sources = ["Balancer_V2"]
enable-slippage-protection = true
api-key = "$YOUR_API_KEY"

# Optionally specify a custom 0x API endpoint with an access key.
# endpoint = "https://gated.api.0x.org/swap/v1/"

# Optionally specify a custom affiliate address.
# affiliate = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"
