node-url = "http://localhost:8545"
absolute-slippage = "40000000000000000" # Denominated in wei, optional
relative-slippage = "0.001" # Percentage in the [0, 1] range
risk-parameters = [0,0,0,0]

[dex]
chain-id = "1"
