# Optionally specify a custom 0x API endpoint with an access key.
# endpoint = "https://gated.api.0x.org/swap/v1/"
# api-key = "abc123"

# Optionally specify a custom affiliate address.
# affiliate = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"

excluded-sources = ["Balancer_V2"]
enable-slippage-protection = true

relative_slippage = "0.1"
absolute_slippage = "0.02"
