endpoint = "https://balancer.sor.eth/api"

# Optionally specify custom Balancer Vault and CoW Protocol settlement contract
# address; omitting these values will use the default addresses:
# vault = "0xBA12222222228d8Ba445958a75a0704d566BF2C8"
# settlement = "0x9008D19f58AAbD9eD0D60971565AA8510560ab41"

relative_slippage = "0.1"
absolute_slippage = "0.02"
