name: flaky test runner
on:
  workflow_dispatch:
    inputs:
      duration:
        description: "How many minutes to run the test"
        required: true
        default: 60
      test_command:
        description: "Which test command to run in a loop"
        required: true
        default: "cargo nextest run -p e2e local_node --test-threads 1 --failure-output final --run-ignored ignored-only"
      target_branch:
        description: "On which branch to run the test"
        required: true
        default: "main"

jobs:
  run-flaky-test:
    timeout-minutes: ${{ github.event.inputs.duration }}
    runs-on: ubuntu-latest
    env:
      # Shrink artifact size by not including debug info. Makes build faster and shrinks cache.
      CARGO_PROFILE_DEV_DEBUG: 0
      CARGO_PROFILE_TEST_DEBUG: 0
      CARGO_TERM_COLOR: always
      TOML_TRACE_ERROR: 1
      FORK_URL_MAINNET: ${{ secrets.FORK_URL_MAINNET }}
      FORK_URL_GNOSIS: ${{ secrets.FORK_URL_GNOSIS }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          ref: ${{ github.event.inputs.target_branch }}

      - run: rustup toolchain install stable --profile minimal
      - uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
      # Start the build process in the background. The following cargo test command will automatically
      # wait for the build process to be done before proceeding.
      - run: cargo build -p e2e --tests &
      - uses: taiki-e/install-action@e4767ccc6762bc4347ef2275c75ea77f5f36e27f # nextest
      - uses: yu-ichiro/spin-up-docker-compose-action@b7808421e139a485cb455f78e66605ca9dbe4334 # v1.2
        with:
          file: docker-compose.yaml
          up-opts: -d db
      - uses: yu-ichiro/spin-up-docker-compose-action@b7808421e139a485cb455f78e66605ca9dbe4334 # v1.2
        with:
          file: docker-compose.yaml
          up-opts: migrations --abort-on-container-failure
      - name: Run test in a loop
        run: |
          attempt=1
          while true; do
            echo "Running test attempt #$attempt"
            if ! ${{ github.event.inputs.test_command }}; then
              exit 1
            fi
            attempt=$((attempt+1))
          done
