use {
    alloy_sol_macro_expander::expand::expand,
    alloy_sol_macro_input::{SolInput, SolInputKind},
    anyhow::{Context, Result},
    proc_macro2::{Span, TokenStream},
    quote::{ToTokens, format_ident},
    rayon::prelude::*,
    std::{
        collections::HashMap,
        fmt::Write,
        path::{Path, PathBuf},
    },
};

/// Header for generated lib.rs files.
const LIB_HEADER: &str = "\
#![allow(unused_imports, unused_attributes, clippy::all, rustdoc::all, non_snake_case)]
//! Auto-generated contract bindings. Do not edit.
";

/// Header for the facade lib.rs.
const FACADE_HEADER: &str = "\
#![allow(unused_imports, unused_attributes, clippy::all, rustdoc::all, non_snake_case)]
//! This crate re-exports per-contract crate bindings.
//! Auto-generated by contracts-generate. Do not edit.
";

/// Cargo.toml template for generated per-contract crates.
const CARGO_TOML_TEMPLATE: &str = "\
# Auto-generated by contracts-generate. Do not edit.
[package]
name = \"{crate_name}\"
version = \"0.1.0\"
edition = \"2024\"
publish = false

[lib]
doctest = false

[dependencies]
alloy-primitives = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-contract = { workspace = true }
alloy-provider = { workspace = true }
anyhow = { workspace = true }

[lints]
workspace = true
";

/// Workspace Cargo.toml template for the generated workspace.
const WORKSPACE_CARGO_TOML: &str = "\
# Auto-generated by contracts-generate. Do not edit.
[workspace]
resolver = \"3\"
members = [
    \"contracts-facade\",
    \"contracts-generated/*\",
]

[workspace.dependencies]
alloy-primitives = { version =  \"1.5.7\", default-features = false }
alloy-sol-types = { version =  \"1.5.7\", default-features = false }
alloy-contract = { version =  \"1.7.3\" }
alloy-provider = { version =  \"1.7.3\", default-features = false }
anyhow = \"1.0.100\"

[workspace.lints.clippy]
all = \"warn\"
";

/// Convert a PascalCase contract name to a kebab-case crate name.
fn to_crate_name(contract_name: &str) -> String {
    format!("cow-contract-{}", contract_name.to_lowercase())
}

/// Convert a contract name to a directory name under contracts-generated/.
fn to_dir_name(contract_name: &str) -> String {
    contract_name.to_lowercase()
}

/// Convert a crate name (kebab-case) to a Rust identifier (underscore_case).
fn to_rust_ident(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

/// Metadata about a generated contract crate, used for facade generation.
struct CrateEntry {
    contract_name: String,
    crate_name: String,
    dir_name: String,
    submodule: Option<String>,
}

#[derive(Default)]
pub struct Module {
    pub contracts: Vec<Contract>,
    pub submodules: Vec<Submodule>,
}

impl Module {
    pub fn add_contract(mut self, contract: Contract) -> Self {
        self.contracts.push(contract);
        self
    }

    pub fn add_submodule(mut self, submodule: Submodule) -> Self {
        self.submodules.push(submodule);
        self
    }

    /// Generate a self-contained Cargo workspace under `output_dir` containing:
    /// - `contracts-generated/<name>/` per-contract crates
    /// - `contracts-facade/` facade crate that re-exports all contracts
    /// - Root workspace `Cargo.toml`
    pub fn generate(self, artifacts_dir: &Path, output_dir: &Path) -> Result<()> {
        let contracts_generated_dir = output_dir.join("contracts-generated");
        let facade_dir = output_dir.join("contracts-facade");

        std::fs::create_dir_all(&contracts_generated_dir)?;
        std::fs::create_dir_all(&facade_dir)?;

        // Collect all contracts with their submodule association, then
        // generate crates in parallel.
        let entries: Vec<CrateEntry> = self
            .contracts
            .iter()
            .map(|c| (c, None))
            .chain(
                self.submodules
                    .iter()
                    .flat_map(|s| s.contracts.iter().map(move |c| (c, Some(s.name.clone())))),
            )
            .collect::<Vec<_>>()
            .into_par_iter()
            .map(|(contract, submodule)| {
                contract.write_crate(artifacts_dir, &contracts_generated_dir)?;
                Ok(CrateEntry {
                    contract_name: contract.name.clone(),
                    crate_name: to_crate_name(&contract.name),
                    dir_name: to_dir_name(&contract.name),
                    submodule,
                })
            })
            .collect::<Result<Vec<_>>>()?;

        let mut entries = entries;
        entries.sort_by_key(|entry| entry.crate_name.clone());

        // Generate the facade crate
        write_facade_lib(&entries, &facade_dir)?;
        write_facade_cargo_toml(&entries, &facade_dir)?;

        // Generate the workspace Cargo.toml
        write_workspace_cargo_toml(output_dir)?;

        Ok(())
    }
}

/// Generate the facade crate's lib.rs file.
fn write_facade_lib(entries: &[CrateEntry], facade_dir: &Path) -> Result<()> {
    let src_dir = facade_dir.join("src");
    std::fs::create_dir_all(&src_dir)?;

    let mut contents = String::from(FACADE_HEADER);

    // Top-level re-exports
    for entry in entries {
        if entry.submodule.is_none() {
            let rust_ident = to_rust_ident(&entry.crate_name);
            writeln!(contents, "pub use {rust_ident} as {};", entry.contract_name)?;
        }
    }

    // Group submodule contracts, preserving insertion order
    let mut submodule_names: Vec<String> = Vec::new();
    let mut submodule_map: HashMap<String, Vec<&CrateEntry>> = HashMap::new();
    for entry in entries {
        if let Some(submod) = &entry.submodule {
            if !submodule_map.contains_key(submod) {
                submodule_names.push(submod.clone());
            }
            submodule_map.entry(submod.clone()).or_default().push(entry);
        }
    }

    // Write submodule blocks in insertion order
    for submod_name in &submodule_names {
        let contracts = &submodule_map[submod_name];
        writeln!(contents, "pub mod {submod_name} {{")?;
        for entry in contracts {
            let rust_ident = to_rust_ident(&entry.crate_name);
            writeln!(
                contents,
                "    pub use {rust_ident} as {};",
                entry.contract_name
            )?;
        }
        writeln!(contents, "}}")?;
    }

    let file: syn::File = syn::parse_file(&contents)?;
    let formatted = prettyplease::unparse(&file);
    std::fs::write(src_dir.join("lib.rs"), formatted)?;

    Ok(())
}

/// Generate the facade crate's Cargo.toml.
fn write_facade_cargo_toml(entries: &[CrateEntry], facade_dir: &Path) -> Result<()> {
    let mut contents = String::from(
        "\
# Auto-generated by contracts-generate. Do not edit.
[package]
name = \"contracts\"
version = \"0.1.0\"
edition = \"2024\"
publish = false

[lib]
doctest = false

[dependencies]
",
    );

    for entry in entries {
        writeln!(
            contents,
            "{} = {{ path = \"../contracts-generated/{}\" }}",
            entry.crate_name, entry.dir_name
        )?;
    }

    contents.push_str("\n[lints]\nworkspace = true\n");

    std::fs::write(facade_dir.join("Cargo.toml"), contents)?;
    eprintln!("  generated facade Cargo.toml");

    Ok(())
}

/// Generate the workspace root Cargo.toml.
fn write_workspace_cargo_toml(output_dir: &Path) -> Result<()> {
    std::fs::write(output_dir.join("Cargo.toml"), WORKSPACE_CARGO_TOML)?;
    eprintln!("  generated workspace Cargo.toml");
    Ok(())
}

pub struct Submodule {
    pub name: String,
    pub contracts: Vec<Contract>,
}

impl Submodule {
    pub fn new<S: ToString>(name: S) -> Self {
        Self {
            name: name.to_string(),
            contracts: vec![],
        }
    }

    pub fn add_contract(mut self, contract: Contract) -> Self {
        self.contracts.push(contract);
        self
    }
}

pub struct Contract {
    pub name: String,
    networks: HashMap<u64, (String, Option<u64>)>,
}

impl Contract {
    pub fn new<S: AsRef<str>>(name: S) -> Self {
        Self {
            name: name.as_ref().to_string(),
            networks: HashMap::new(),
        }
    }

    pub fn with_networks<S, I>(mut self, networks: I) -> Self
    where
        S: AsRef<str>,
        I: IntoIterator<Item = (u64, (S, Option<u64>))>,
    {
        for (id, (address, block_number)) in networks.into_iter() {
            self.networks
                .insert(id, (address.as_ref().to_string(), block_number));
        }
        self
    }

    fn artifacts_path(&self, artifacts_dir: &Path) -> PathBuf {
        artifacts_dir.join(&self.name).with_extension("json")
    }

    /// Generate the Rust code for this contract's bindings.
    fn generate_code(&self, artifacts_dir: &Path) -> Result<TokenStream> {
        let bindings_path = self.artifacts_path(artifacts_dir);
        let mut macrogen = SolMacroGen::new(bindings_path, self.name.clone());
        generate_binding(&mut macrogen, true)?;
        let mut expansion = macrogen
            .expansion
            .expect("if the expansion failed, it should have errored earlier");

        let module_name_ident = format_ident!("{}", self.name);
        let instance_name_ident = format_ident!("{}Instance", self.name);
        let instance = quote::quote! {
            pub type Instance = #module_name_ident :: #instance_name_ident<::alloy_provider::DynProvider>;
        };
        expansion.extend(instance);

        if !self.networks.is_empty() {
            let networks = self
                .networks
                .iter()
                .map(|(&chain_id, info)| NetworkArm(chain_id, (info.0.clone(), info.1)));
            let deployment_info = quote::quote! {
                use {
                    std::{
                        sync::LazyLock,
                        collections::HashMap
                    },
                    anyhow::{Result, Context},
                    alloy_primitives::{address, Address},
                    alloy_provider::{Provider, DynProvider},
                };

                pub const fn deployment_info(chain_id: u64) -> Option<(Address, Option<u64>)> {
                    match chain_id {
                        #( #networks ,)*
                        _ => None
                    }
                }

                pub const fn deployment_address(chain_id: &u64) -> Option<::alloy_primitives::Address> {
                    match deployment_info(*chain_id) {
                        Some((address, _)) => Some(address),
                        None => None,
                    }
                }

                pub const fn deployment_block(chain_id: &u64) -> Option<u64> {
                    match deployment_info(*chain_id) {
                        Some((_, block)) => block,
                        None => None,
                    }
                }

                impl Instance {
                    pub fn deployed(provider: &DynProvider) -> impl Future<Output = Result<Self>> + Send {
                        async move {
                            let chain_id = provider
                                .get_chain_id()
                                .await
                                .context("could not fetch current chain id")?;

                            let (address, _deployed_block) = deployment_info(chain_id)
                                .with_context(|| format!("no deployment info for chain {chain_id:?}"))?;

                            Ok(Instance::new(
                                address,
                                provider.clone(),
                            ))
                        }
                    }
                }
            };
            expansion.extend(deployment_info);
        }

        Ok(expansion)
    }

    /// Write a per-contract crate to the contracts-generated directory.
    fn write_crate(&self, artifacts_dir: &Path, contracts_generated_dir: &Path) -> Result<()> {
        let crate_name = to_crate_name(&self.name);
        let dir_name = to_dir_name(&self.name);
        let crate_dir = contracts_generated_dir.join(&dir_name);
        let src_dir = crate_dir.join("src");
        std::fs::create_dir_all(&src_dir)?;

        // Generate Cargo.toml
        let cargo_toml = CARGO_TOML_TEMPLATE.replace("{crate_name}", &crate_name);
        std::fs::write(crate_dir.join("Cargo.toml"), cargo_toml)?;

        // Generate lib.rs
        let token_stream = self.generate_code(artifacts_dir)?;
        let mut buffer = String::from(LIB_HEADER);
        write!(buffer, "{}", token_stream)?;
        let file: syn::File = syn::parse_file(&buffer)
            .with_context(|| format!("parsing generated code for {}", self.name))?;
        let formatted = prettyplease::unparse(&file);
        std::fs::write(src_dir.join("lib.rs"), formatted)?;

        eprintln!("  generated crate: {crate_name} (contracts-generated/{dir_name})");
        Ok(())
    }
}

fn generate_binding(instance: &mut SolMacroGen, all_derives: bool) -> Result<()> {
    let input = instance
        .get_sol_input()
        .map_err(|err| anyhow::anyhow!("{:?}", err))?
        .normalize_json()
        .map_err(|err| anyhow::anyhow!("{:?}", err))?;
    let SolInput {
        attrs: _,
        path: _,
        kind,
    } = input;

    let tokens = match kind {
        SolInputKind::Sol(mut file) => {
            let sol_attr: syn::Attribute = if all_derives {
                syn::parse_quote! {
                    #[sol(rpc, alloy_sol_types = alloy_sol_types, alloy_contract =
                alloy_contract, all_derives = true)]
                }
            } else {
                syn::parse_quote! {
                    #[sol(rpc, alloy_sol_types = alloy_sol_types, alloy_contract =
                alloy_contract)]
                }
            };
            file.attrs.push(sol_attr);
            expand(file)?
        }
        _ => unreachable!(),
    };

    instance.expansion = Some(tokens);
    Ok(())
}

struct NetworkArm(u64, (String, Option<u64>));

impl ToTokens for NetworkArm {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let chain_id = self.0;
        let address = &self.1.0;
        let block_number = match self.1.1 {
            Some(block) => quote::quote! {Some(#block)},
            None => quote::quote! {None},
        };
        tokens.extend(quote::quote! {
           #chain_id => Some((::alloy_primitives::address!(#address), #block_number))
        });
    }
}

/// SolMacroGen implementation vendored from
/// <https://github.com/foundry-rs/foundry/blob/cc24b6b74978e72b7330ad7d4b39140e9ee33deb/crates/sol-macro-gen/src/sol_macro_gen.rs>
struct SolMacroGen {
    path: PathBuf,
    name: String,
    expansion: Option<TokenStream>,
}

impl SolMacroGen {
    fn new(path: PathBuf, name: String) -> Self {
        Self {
            path,
            name,
            expansion: None,
        }
    }

    fn get_sol_input(&self) -> Result<SolInput> {
        let path = self.path.to_string_lossy().into_owned();
        let name = proc_macro2::Ident::new(&self.name, Span::call_site());
        let tokens = quote::quote! {
            #[sol(ignore_unlinked)]
            #name,
            #path
        };

        let sol_input: SolInput = syn::parse2(tokens).context("failed to parse input")?;

        Ok(sol_input)
    }
}
